### PR TITLE
fix: cannot specify all protocols and specific ports egress

### PR DESCRIPTION
**Pull request by scottschreckengaust**
> You may not specify all protocols and specific ports. Please specify each protocol and port range combination individually, or all protocols and no port range.

### CODE REVIEW

**Comment by scottschreckengaust** [comment]
I get this error when attempting to deploy:

```
│ Error: updating VPC Security Group Rule (sgr-08a7211c0c97ea93e)
│ 
│   with module.genai_doc_ingestion.module.networking_resources.aws_vpc_security_group_egress_rule.to_internet,
│   on .terraform/modules/genai_doc_ingestion/modules/networking-resources/main.tf line 23, in resource "aws_vpc_security_group_egress_rule" "to_internet":
│   23: resource "aws_vpc_security_group_egress_rule" "to_internet" {
│ 
│ operation error EC2: ModifySecurityGroupRules, https response error StatusCode: 400, RequestID: 0a9f7fb3-f845-4273-affe-5c2451ff50c2, api error
│ InvalidParameterValue: You may not specify all protocols and specific ports. Please specify each protocol and port range combination individually, or all
│ protocols and no port range.
╵
```

**Review by MichaelWalker-git — APPROVED** [review]

**Review by MichaelWalker-git — APPROVED** [review]

**Pull request merged**
